### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by dragarok** [domoritz/csv2parquet#34]
Is there a way to write multiple parquet files instead of one using the script?

**Comment by domoritz** [comment]
No. 

What do you mean by multiple files? Split into chunks? I'd be happy to review a pull request towards this goal.

**Comment by dragarok** [comment]
Split into chunks so that files can be read in distributed fashion. Example is how dask writes parquet files into chunks. https://mungingdata.com/dask/read-csv-to-parquet/#:~:text=Dask%20is%20a%20great%20technology%20for%20converting%20CSV,files%20should%20generally%20be%20avoided%20in%20data%20products. You have done an amazing work with this.

**Comment by dragarok** [comment]
I am not a rust developer. I wanted to create an exe for this process using python which got hectic. Landed on your repo. But, since I have to read in big files, they are overflowing in Python due to which I need multiple files in Parquet.

**Comment by domoritz** [comment]
I learned rust with Arrow. I think to write multiple files, we would need to change the code. Here are the arrow rust docs: https://github.com/apache/arrow-rs. I'm closing this since I won't be doing this but I would be happy to review a pull request.
