### ISSUE TITLE
parse timestamps?

### ISSUE THREAD

**Issue by enjalot** [domoritz/csv2parquet#39]
Unlike the DuckDB CSV import this doesn't seem to recognize date strings and parse them into timestamps. would that be hard to add?

**Comment by domoritz** [comment]
I rely on arrow-rs' type inference. Can you file an issue there?

**Comment by enjalot** [comment]
submitted here https://github.com/apache/arrow-rs/issues/1060

**Comment by domoritz** [comment]
Thank you. Once they add support, we will get parsing for free here when I update the dependency.
