### ISSUE TITLE
Feature: allow user to specify compression level through CLI argument

### ISSUE THREAD

**Issue by corneliusroemer** [domoritz/csv2parquet#41]
This should be possible through the arrow-rs crate, one just needs to add the argument for it.

**Comment by domoritz** [comment]
Makes sense. Want to send a pull request?

**Comment by corneliusroemer** [comment]
If I have time :)

I'm trying to get stuff done at the moment looking for the best way to turn csv -> parquet. `duckdb` is ahead right now because they accept `gz` compressed input files.

But this tool definitely has potential.

**Comment by domoritz** [comment]
Sounds good. I just made this tool in my free time since I wanted an easy tool to get parquet/arrow and it's a pretty light wrapper around arrow rs. My goal is to track their support but not add too much logic here.

**Comment by corneliusroemer** [comment]
Totally understandable. That's what I thought it was. Works really well, I'm surprised there's no official CLI wrapper.

**Comment by domoritz** [comment]
I didn't see the compression level in the API at https://docs.rs/parquet/6.4.0/parquet/index.html.
