### ISSUE TITLE
Doc: Improve clarity by renaming any -> all

### ISSUE THREAD

**Issue by corneliusroemer** [domoritz/csv2parquet#42]
In the help text it often says `any` when I feel like `all` would be clearer. Since these flags seem to be all or nothing.

Any is often used in the context of "at least one" which threw me off here.

Example:
```
Sets flag to enable/disable dictionary encoding for any column
```

**Comment by domoritz** [comment]
I think I copied the comments from arrow rs. Please check and file an issue there if I did.

**Comment by corneliusroemer** [comment]
You were right, it comes from upstream. Opened an issue there: https://github.com/apache/arrow-rs/issues/1064
