### ISSUE TITLE
NULLs not handled

### ISSUE THREAD

**Issue by jakub-auger** [domoritz/csv2parquet#82]
parquet supports nulls
is there a way to force certain values (blanks, or literal NULL keyword) to be created as NULLs in the output file?
like some kind of -switch '' or -switch 'NULL' which'll convert those values into a proper parquet NULL

background:
I have a CSV dump out of a database
some columns are nulls - this becomes an issue with inferring schemas especially for the numeric and date cols - they get inferred as strings in the parquet file

this messes with querying the parquet files in all sorts of ways

**Comment by domoritz** [comment]
Thanks for the issue. I looked at the arrow rust docs and couldn't find an obvious way to handle null values in CSV. In the code, I found that empty strings are treated as null: https://github.com/apache/arrow-rs/blob/c08e5324d11a8a2b9998d0d625876815f4954968/arrow/src/csv/reader.rs#L217. So for now, you need to use blank values. If you want support for custom values, you need to file an enhancement request for arrow-rs first.
